### ISSUE TITLE
msls_options_get_permalink filter not working with WooCommerce product_cat

### ISSUE THREAD

**Issue by llos** [lloc/Multisite-Language-Switcher#118] opened 2018-05-09 09:21 UTC
I’m using `msls_options_get_permalink` to control de rewrite of some custom taxonomies and it works fine. However, it doesn’t work fine with product_cat woocommerce taxnomy. It seem to be some kind of conflict with its rewrite, maybe because you can choose it from back-end?
This issue has been already posted here https://wordpress.org/support/topic/msls_options_get_permalink-filter-not-working-with-woocommerce-product_cat/

**Comment by llos** [comment] 2019-05-29 14:04
Hi @lloc,

Any updates regarding this problem? Is there anything we can do to help you debug this? Do you have any idea of where the problem can come from?

Thank you in advance.

**Comment by Tepeek** [comment] 2019-09-26 15:43
Hi guys,
I have the same problem. I am trying to solve this problem... But I've been trying for over a year. It doesn't works with product-cat and product-tag. Even though the custom filter below, works with everything else on the website, except with WooCommerce. I'll let you know about the progress.
![filtre-msls](https://user-images.githubusercontent.com/27774101/65703433-0f17c900-e085-11e9-8030-a350fed11930.jpg)

**Comment by Tepeek** [comment] 2019-10-02 13:31
Hi, There, it's done!
I ended up finding a solution... I hope it's the right one. In my case, it works very well for product categories as well as for product tags.

Here's what I changed in the file "includes/MslsOptionsTax.php", line 128:

    `/**
	 * Wraps the call to get_term_link
	 *
	 * @param int $term_id
	 *
	 * @return string
	 */
	public function get_term_link( $term_id ) {
		if ( ! empty( $term_id ) ) {
			$taxonomy = $this->get_tax_query();
			if ( ! empty( $taxonomy ) ) {
				$link = get_term_link( $term_id, $taxonomy );
				if ( ! is_wp_error( $link ) ) {
					return $link;
				}
			}
		}
		return apply_filters( 'check_url', get_term_link( $term_id ), $this );
	}`

Enjoy!

**Comment by lloc** [comment] 2019-10-05 06:24
Interesting would you mind to send a pull-request? Or do you prefer that just I test and integrate your code?

**Comment by Tepeek** [comment] 2019-10-05 10:16
Hi Dennis and frankly a big congratulations for your great plugin! Ok, For my part, I did tests with the latest versions of Woocommerce and WordPress; Thus that PHP 7.0.x. Now, with your approval, I would like it to be integrated in a future version of your Plugin.

I read somewhere that Woocommerce is not what you prefer... or at least you did not develop MSLS for it. Anyway, I can confirm that it works very well! For it to be perfect, maybe make sure the x-default tag: 

> rel="alternate" hreflang="x-default"

present everywhere, not just when there are no translations, because, for SEO rules, if an user does not find his native language, if possible, must indicate the origin language of the website. What do you think about it?

Voilà !

**Comment by lloc** [comment] 2024-11-14 11:54
Close this in favor of: https://github.com/lloc/Multisite-Language-Switcher/issues/399

**Comment by lloc** [comment] 2024-11-14 11:55
Close this in favor of: https://github.com/lloc/Multisite-Language-Switcher/issues/399

**Closed by lloc** 2024-11-14 11:55 UTC
Labels: Bug, Woo
